# Generated by Django 4.0.3 on 2022-03-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Utilisateurs'},
        ),
    ]
