# Generated by Django 4.0.3 on 2022-03-19 15:20

from django.db import migrations, models
import monument.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=10000)),
                ('image', models.ImageField(blank=True, null=True, upload_to=monument.models.upload_location)),
                ('year', models.CharField(blank=True, max_length=50)),
                ('Latitude', models.FloatField(blank=True)),
                ('longitude', models.FloatField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
