# Generated by Django 4.0.3 on 2022-03-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monument', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monument',
            old_name='name',
            new_name='title',
        ),
    ]
