# Generated by Django 4.0.3 on 2022-03-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monument', '0002_rename_name_monument_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monument',
            old_name='Latitude',
            new_name='latitude',
        ),
    ]
