# Generated by Django 4.0.3 on 2022-03-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monument', '0003_rename_latitude_monument_latitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monument',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monument',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
