# Generated by Django 4.0.3 on 2022-03-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monument', '0004_alter_monument_latitude_alter_monument_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monument',
            name='latitude',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='monument',
            name='longitude',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
