# Generated by Django 4.0.3 on 2022-03-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monument', '0006_savedmonument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedMonument',
        ),
    ]
