# Generated by Django 4.0.3 on 2022-03-22 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monument', '0007_delete_savedmonument'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='saved',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
